services:
  # === BACKEND (Laravel) ===
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # === nginx ===
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - app-network

  # === BANCO DE DADOS ===
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

 # === FRONTEND (Quasar) ===
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quasar-frontend
    volumes:
      - ./frontend:/var/www/html/frontend
    ports:
      - "9000:9090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
